version: '3'
services:
  server:
    build: .
    ports:
     - "8000:8000"
    command: ["python", "server.py"]
    environment:
    - REDIS_HOST=redis
    links:
    - redis
  worker:
    build: .
    ports:
    - "4000:4000"
    command: ["python", "worker.py"]
    environment:
    - REDIS_HOST=redis
    links:
    - redis
  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
